### ISSUE TITLE
[BUG] Local ws://localhost:8080/log websocket endpoint send binary content in WS text frames

### ISSUE THREAD

**Issue by elrondex** [ElrondNetwork/elrond-go#3502]
<details>
<summary>Standard websocket client/library can't connect to  ws://localhost:8080/log endpoint </summary>
<pre>
Application version string: T1.2.23.0
Same problem to more versions.
Hosting VPS: 
  NAME="Ubuntu"
  VERSION="20.04.2 LTS (Focal Fossa)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 20.04.2 LTS"
  VERSION_ID="20.04"
</pre>
</details>

In order to extract logs form local node, I try to connect with  websocket  elixir library to ws://localhost:8080/log endpoint
Same test was done with `jetty websocket client`
```
      <dependency>
            <groupId>org.eclipse.jetty.websocket</groupId>
            <artifactId>websocket-client</artifactId>
            <version>9.4.44.v20210927</version>
        </dependency>
```
In in both cases I have error related to utf-8 encode (Invalid content in websocket  text frame) 
For instance: **Not valid UTF8! byte 85 in state 0**

```
Socket Connected: WebSocketSession[websocket=JettyListenerEventDriver[com.elrond.EventSocket],behavior=CLIENT,connection=WebSocketClientConnection@3f520942::SocketChannelEndPoint@43ca86d3{l=/127.0.0.1:51737,r=localhost/127.0.0.1:8080,OPEN,fill=-,flush=-,to=48/300000}{io=0/0,kio=0,kro=1}->WebSocketClientConnection@3f520942[s=ConnectionState@1da3c177[OPENING],f=Flusher@4138b664[IDLE][queueSize=0,aggregateSize=-1,terminated=null],g=Generator[CLIENT,validating],p=Parser@4115a176[ExtensionStack,s=START,c=0,len=0,f=null]],remote=WebSocketRemoteEndpoint@567e5b99[batching=true],incoming=JettyListenerEventDriver[com.elrond.EventSocket],outgoing=ExtensionStack[queueSize=0,extensions=[],incoming=org.eclipse.jetty.websocket.common.WebSocketSession,outgoing=org.eclipse.jetty.websocket.client.io.WebSocketClientConnection]]
Awaiting closure from remote
org.eclipse.jetty.websocket.api.BadPayloadException: org.eclipse.jetty.util.Utf8Appendable$NotUtf8Exception: Not valid UTF8! byte 85 in state 0
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:169)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:326)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:202)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:225)
	at org.eclipse.jetty.websocket.common.Parser.parseSingleFrame(Parser.java:259)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:459)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:440)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
```

Relevant code is here 
https://github.com/ElrondNetwork/elrond-go/blob/master/api/logs/logSender.go#L154

where we write message on ws connetion as websocket.TextMessage but data is simple binary content (It is not valid utf-8 content)
```
func (ls *logSender) sendMessage() (shouldStop bool) {
	data, ok := ls.writer.ReadBlocking()
	if !ok {
		return true
	}

	err := ls.conn.WriteMessage(websocket.TextMessage, data)
``` 

To fix that we need to send ws frame as Binary and to ensure current ws clients that consume this data it handle correct this content.

If my find is correct: https://github.com/ElrondNetwork/elrond-go/blob/master/cmd/logviewer/main.go#L285
msgType is not checked for Text/Binary and it is always read as binary `func outputMessage(message []byte) {` 

```
func listeningOnWebSocket() {
	for {
		msgType, message, err := webSocket.ReadMessage()
		if msgType == websocket.CloseMessage {
			return
		}
		if err == nil {
			outputMessage(message)
			continue
		}

		_, isConnectionClosed := err.(*websocket.CloseError)
		if !isConnectionClosed {
			log.Error("logviewer websocket error, retrying in %v...", "error", err.Error())
		} else {
			log.Error(fmt.Sprintf("logviewer websocket terminated by the server side, retrying in %v...", retryDuration), "error", err.Error())
		}
		return
	}
}
``` 

This is relative easy change and I can provide PR if Elrond team is fine with this.

@elrondex

**Comment by gabi-vuls** [comment]
Hello elrondex,
Thank you for your feedback. 

That endpoint was meant for `elrond-go/cmd/logviewer` and `elrond-go/cmd/termui`.
It was not designed to be used in other circumstances.

**Comment by elrondex** [comment]
No problem,
thanks for reply 

@elrondex
