### ISSUE TITLE
Setup a Local Testnet on MacOS

### ISSUE THREAD

**Issue by dan-merlea** [ElrondNetwork/elrond-go#3599]
I'm having trouble configuring a local testnet on mac.

Doing the easy way I get this error:

```
$ erdpy testnet config
Traceback (most recent call last):
  File "/Users/<user>/Library/Python/3.9/bin/erdpy", line 8, in <module>
    sys.exit(main())
  File "/Users/<user>/Library/Python/3.9/lib/python/site-packages/erdpy/cli.py", line 32, in main
    _do_main()
  File "/Users/<user>/Library/Python/3.9/lib/python/site-packages/erdpy/cli.py", line 44, in _do_main
    scope.initialize()
  File "/Users/<user>/Library/Python/3.9/lib/python/site-packages/erdpy/scope.py", line 25, in initialize
    testnet_config = TestnetConfiguration.from_file(testnet_toml)
  File "/Users/<user>/Library/Python/3.9/lib/python/site-packages/erdpy/testnet/config.py", line 104, in from_file
    return cls(final_config)
  File "/Users/<user>/Library/Python/3.9/lib/python/site-packages/erdpy/testnet/config.py", line 65, in __init__
    default_tag = erdpy.config.get_latest_semver_from_directory(parent_folder)
  File "/Users/<user>/Library/Python/3.9/lib/python/site-packages/erdpy/config.py", line 263, in get_latest_semver_from_directory
    raise Exception(f'no versions found in {directory}')
Exception: no versions found in /Users/<user>/elrondsdk/elrond_go
```

The folder `/Users/<user>/elrondsdk/elrond_go` exists.

Trying the advanced steps.

```
./prerequisites.sh
Your operating system was not identified. The required packages were not installed, however they could still be part of your system.
```

If I continue with `./config.sh` 

```
$ ./config.sh 
Building Configuration Generator...
~/Elrond/elrond-deploy-go/cmd/filegen ~/Elrond/testnet
/Users/<user>/Elrond/elrond-go/scripts/testnet/include/build.sh: line 31: go: command not found
~/Elrond/testnet
~/Elrond/testnet ~/Elrond/testnet
mv: rename /Users/<user>/Elrond/elrond-deploy-go/cmd/filegen/filegen to ./filegen/filegen: No such file or directory
Configuration Generator built...
~/Elrond/testnet
Generating configuration using values from scripts/variables.sh...
~/Elrond/testnet/filegen ~/Elrond/testnet
/Users/<user>/Elrond/elrond-go/scripts/testnet/include/config.sh: line 6: ./filegen: No such file or directory
~/Elrond/testnet
~/Elrond/testnet ~/Elrond/testnet
cp: ./filegen/output/genesis.json: No such file or directory
cp: ./filegen/output/nodesSetup.json: No such file or directory
cp: ./filegen/output/*.pem: No such file or directory
Configuration files copied from the configuration generator to the working directories of the executables.
~/Elrond/testnet
~/Elrond/testnet ~/Elrond/testnet
~/Elrond/testnet
~/Elrond/testnet/seednode/config ~/Elrond/testnet
sed: 1: "p2p_edit.toml": extra characters at the end of p command
Updated configuration for the Seednode.
~/Elrond/testnet
~/Elrond/testnet ~/Elrond/testnet
mkdir: -p: File exists
Configuration files copied from the Node to the working directories of the executables.
~/Elrond/testnet
~/Elrond/testnet/node/config ~/Elrond/testnet
sed: 1: "p2p_edit.toml": extra characters at the end of p command
cp: nodesSetup.json: No such file or directory
sed: 1: "nodesSetup_edit.json": extra characters at the end of n command
sed: 1: "nodesSetup_edit.json": extra characters at the end of n command
sed: 1: "config_validator.toml": command c expects \ followed by text
sed: 1: "config_observer.toml": command c expects \ followed by text
cp: nodesSetup_edit.json: No such file or directory
rm: nodesSetup_edit.json: No such file or directory
Updated configuration for Nodes.
~/Elrond/testnet
~/Elrond/testnet ~/Elrond/testnet
cp: ./node/config/walletKey.pem: No such file or directory
Copied configuration for the Proxy.
~/Elrond/testnet
~/Elrond/testnet/proxy/config ~/Elrond/testnet
sed: 1: "config_edit.toml": command c expects \ followed by text
Updated configuration for the Proxy.
~/Elrond/testnet
~/Elrond/testnet/node/config ~/Elrond/testnet
cat: nodesSetup.json: No such file or directory
sed: 1: "config_observer.toml": command c expects \ followed by text
sed: 1: "config_validator.toml": command c expects \ followed by text
~/Elrond/testnet
```

**Comment by dan-merlea** [comment]
I managed to start the mini-testnet by running the config command outside of the folder not like in the docs:

Docs:
```
$ cd MySandbox
$ erdpy testnet config
```

Working version:
```
$ cd MySandbox
$ cd ../
$ erdpy testnet config
```

The advanced one, still the same issue

**Comment by andreibancioiu** [comment]
Hello @dan-merlea!

Thank you for reporting the issue & sorry for the delay :pray: 

Indeed, we recommend the simpler `erdpy testnet` for most purposes (especially for MacOS).

The first encountered issue might have been related to an initial error while running `erdpy testnet prerequisites`.

Furthermore, `erdpy testnet config` must be executed within the folder that contains the `testnet.toml` file. 

Possible explanation for your second issue: it's possible that your command `mkdir MySandbox && cd MySandbox` failed in the first place (probably existing folder `MySandbox`) and thus the `touch testnet.toml` (the command depicted in the docs) created the file in a different place than specified one.

In case of future issues related to the **erdpy local testnet**, please submit them here:
https://github.com/ElrondNetwork/elrond-sdk-erdpy/issues

This issue will be closed now.
